# Write your MySQL query statement below
WITH CTE1 AS(
    SELECT 
    ID,
    CASE WHEN COUNTRY IS NULL THEN "null" ELSE COUNTRY END AS COUNTRY,
    AMOUNT,
    CASE
        WHEN STATE = 'approved' THEN 1
        ELSE 0
    END AS STATE,
    TRANS_DATE
    FROM TRANSACTIONS
),

CTE2 AS(
    SELECT DATE_FORMAT(TRANS_DATE, "%Y-%m") AS MONTH,
    CASE WHEN COUNTRY IS NULL THEN "null" ELSE COUNTRY END AS COUNTRY,
    COUNT(STATE) AS TRANS_COUNT,
    SUM(STATE) AS APPROVED_COUNT,
    SUM(AMOUNT) AS TRANS_TOTAL_AMOUNT
    FROM CTE1
    GROUP BY MONTH, COUNTRY
),

CTE3 AS(
    SELECT 
    DATE_FORMAT(TRANS_DATE, "%Y-%m") AS MONTH,
    CASE WHEN COUNTRY IS NULL THEN "null" ELSE COUNTRY END AS COUNTRY,
    SUM(AMOUNT) AS APPROVED_TOTAL_AMOUNT
    FROM CTE1
    WHERE STATE = 1
    GROUP BY MONTH, COUNTRY
),

CTE4 AS(
    SELECT 
    CTE2.MONTH,
    CTE2.COUNTRY,
    CTE2.TRANS_COUNT,
    CTE2.APPROVED_COUNT,
    CTE2.TRANS_TOTAL_AMOUNT,
    CASE
        WHEN CTE3.APPROVED_TOTAL_AMOUNT IS NULL THEN 0
        ELSE CTE3.APPROVED_TOTAL_AMOUNT
    END AS APPROVED_TOTAL_AMOUNT
    FROM CTE3 RIGHT JOIN CTE2
    ON CTE2.MONTH = CTE3.MONTH AND CTE2.COUNTRY = CTE3.COUNTRY
)

SELECT 
    MONTH,
    CASE WHEN COUNTRY = "null" THEN NULL ELSE COUNTRY END AS COUNTRY,
    TRANS_COUNT,
    APPROVED_COUNT,
    TRANS_TOTAL_AMOUNT,
    APPROVED_TOTAL_AMOUNT
FROM CTE4
;