(SELECT
U.NAME AS RESULTS
FROM MOVIERATING MR LEFT JOIN USERS U ON MR.USER_ID = U.USER_ID
GROUP BY U.NAME, U.USER_ID
ORDER BY COUNT(MR.RATING) DESC, U.NAME ASC LIMIT 1)

UNION ALL

(SELECT
M.TITLE AS RESULTS
FROM MOVIES M LEFT JOIN MOVIERATING MR ON M.MOVIE_ID = MR.MOVIE_ID
WHERE YEAR(CREATED_AT) = 2020 AND MONTH(CREATED_AT) = 2
GROUP BY M.TITLE, M.MOVIE_ID
ORDER BY AVG(MR.RATING) DESC, TITLE ASC LIMIT 1
)
;