WITH CTE1 AS (
    SELECT
    MACHINE_ID,
    PROCESS_ID,
    CASE WHEN ACTIVITY_TYPE = 'start' THEN TIMESTAMP END AS START_TIME,
    CASE WHEN ACTIVITY_TYPE = 'end' THEN TIMESTAMP END AS END_TIME
    FROM ACTIVITY
    ORDER BY MACHINE_ID ASC, PROCESS_ID ASC
),
CTE2 AS (
    SELECT
    MACHINE_ID,
    PROCESS_ID,
    CASE WHEN START_TIME IS NULL THEN 0 ELSE START_TIME END AS START_TIME,
    CASE WHEN END_TIME IS NULL THEN 0 ELSE END_TIME END AS END_TIME
    FROM CTE1
),
CTE3 AS (
    SELECT
    MACHINE_ID,
    PROCESS_ID,
    SUM(START_TIME) AS START_TIME2,
    SUM(END_TIME) AS END_TIME2
    FROM CTE2
    GROUP BY MACHINE_ID, PROCESS_ID
)
SELECT
MACHINE_ID,
ROUND(AVG(END_TIME2 - START_TIME2), 3) AS PROCESSING_TIME
FROM CTE3
GROUP BY MACHINE_ID
;