SELECT EMPLOYEE_ID, DEPARTMENT_ID
FROM (
    SELECT
    EMPLOYEE_ID,
    DEPARTMENT_ID,
    COUNT(DEPARTMENT_ID) OVER (PARTITION BY EMPLOYEE_ID) AS DEPT_COUNT,
    PRIMARY_FLAG
    FROM EMPLOYEE
) E
WHERE PRIMARY_FLAG = 'Y' AND DEPT_COUNT > 1 OR DEPT_COUNT = 1 AND PRIMARY_FLAG = 'N';