WITH CTE1 AS(
    SELECT
    S.USER_ID,
    S.TIME_STAMP,
    CASE
        WHEN C.ACTION IS NULL OR C.ACTION = "timeout" THEN 0
        ELSE 1
    END AS ACTION

    FROM SIGNUPS S LEFT JOIN CONFIRMATIONS C ON S.USER_ID = C.USER_ID
),

CTE2 AS(
    SELECT
    USER_ID,
    SUM(ACTION) AS SUMM,
    COUNT(ACTION) AS COUN
    FROM CTE1
    GROUP BY USER_ID
)

SELECT 
USER_ID,
ROUND(SUMM/COUN, 2) AS CONFIRMATION_RATE
FROM CTE2
;