-- Runtime 873 ms and beats 91.85% of submissions
SELECT
    DEPARTMENT,
    EMPLOYEE,
    SALARY
FROM(
    SELECT
        E.NAME AS EMPLOYEE,
        E.SALARY,
        D.NAME AS DEPARTMENT,
        DENSE_RANK() OVER (PARTITION BY E.DEPARTMENTID ORDER BY E.SALARY DESC) AS SALARY_RANK
    FROM EMPLOYEE E LEFT JOIN DEPARTMENT D ON E.DEPARTMENTID = D.ID
    ORDER BY E.DEPARTMENTID DESC, E.SALARY DESC
) I
WHERE SALARY_RANK <= 3;
