WITH CTE1 AS(
    SELECT
        PLAYER_ID,
        EVENT_DATE,
        FIRST_VALUE(EVENT_DATE) OVER(PARTITION BY PLAYER_ID ORDER BY EVENT_DATE) AS FIRST_LOGIN,
        LEAD(EVENT_DATE, 1) OVER(PARTITION BY PLAYER_ID ORDER BY EVENT_DATE) AS NEXT_DATE_LOGIN
    FROM ACTIVITY
),

CTE2 AS(
    SELECT * FROM CTE1
        WHERE EVENT_DATE = FIRST_LOGIN 
        AND NEXT_DATE_LOGIN IS NOT NULL 
        AND DATEDIFF(NEXT_DATE_LOGIN, EVENT_DATE) = 1
)

SELECT ROUND(
    (SELECT COUNT(DISTINCT PLAYER_ID) FROM CTE2) / (SELECT COUNT(DISTINCT PLAYER_ID) FROM CTE1), 2) 
    AS FRACTION;