-- Runtime - 275 ms, beats 96.82% of other submissions.
SELECT
FRIEND_ID AS ID,
COUNT(FRIEND_ID) AS NUM
FROM(
    SELECT
        R.REQUESTER_ID AS FRIEND_ID
    FROM REQUESTACCEPTED R
    UNION ALL
    SELECT
        A.ACCEPTER_ID AS FRIEND_ID
    FROM REQUESTACCEPTED A
) I
GROUP BY FRIEND_ID
ORDER BY NUM DESC LIMIT 1
;