WITH CTE1 AS(
    SELECT
    PRODUCT_ID,
    YEAR AS FIRST_YEAR,
    QUANTITY,
    PRICE,
    RANK() OVER (PARTITION BY PRODUCT_ID ORDER BY YEAR) AS YEAR_RANK

    FROM SALES
)

SELECT
    PRODUCT_ID,
    FIRST_YEAR,
    QUANTITY,
    PRICE
FROM CTE1 WHERE YEAR_RANK = 1;