-- Write your MySQL query statement below
WITH CTE1 AS(
    SELECT
    DELIVERY_ID,
    CUSTOMER_ID,
    ORDER_DATE,
    CUSTOMER_PREF_DELIVERY_DATE,
    RANK() OVER (PARTITION BY CUSTOMER_ID ORDER BY ORDER_DATE ASC) AS RANK_ORDERS,
    CASE
        WHEN ORDER_DATE = CUSTOMER_PREF_DELIVERY_DATE THEN 1
        ELSE 0
    END AS IMMEDIATE_DELIVERY
    FROM DELIVERY
),

CTE2 AS(
    SELECT * FROM CTE1
    WHERE RANK_ORDERS = 1
)

SELECT
ROUND((SUM(IMMEDIATE_DELIVERY) / COUNT(IMMEDIATE_DELIVERY)) * 100, 2) AS IMMEDIATE_PERCENTAGE
FROM CTE2
;