WITH CTE1 AS(
    SELECT
    VISITED_ON,
    SUM(AMOUNT) AS PER_DAY_SUM
    FROM CUSTOMER
    GROUP BY VISITED_ON
),

CTE2 AS(
SELECT
    VISITED_ON,
    ROUND(SUM(PER_DAY_SUM) OVER 
        (ORDER BY VISITED_ON ROWS BETWEEN 6 PRECEDING AND CURRENT ROW), 2) AS AMOUNT,
    ROUND(AVG(PER_DAY_SUM) OVER 
        (ORDER BY VISITED_ON ROWS BETWEEN 6 PRECEDING AND CURRENT ROW), 2) AS AVERAGE_AMOUNT
FROM CTE1

)
SELECT * FROM CTE2
WHERE DATEDIFF(VISITED_ON, (SELECT MIN(VISITED_ON) FROM CTE2)) >= 6;