SELECT
    "Low Salary" AS CATEGORY,
    SUM(INCOME < 20000) AS ACCOUNTS_COUNT
FROM
    ACCOUNTS
UNION
SELECT
    "Average Salary" AS CATEGORY,
    SUM(INCOME BETWEEN 20000 AND 50000) AS ACCOUNT_COUNT
FROM
    ACCOUNTS
UNION
SELECT
    'High Salary' AS CATEGORY,
    SUM(INCOME > 50000) AS ACCOUNTS_COUNT
FROM
    ACCOUNTS;