SELECT
    POST_DATE, 
    SUM(CASE WHEN POST_KEYWORDS LIKE '%spam%' THEN 1 ELSE 0 END) * 100.0 / COUNT(*)
FROM FACEBOOK_POSTS
WHERE POST_ID IN (SELECT DISTINCT POST_ID FROM FACEBOOK_POST_VIEWS)
GROUP BY POST_DATE
;