SELECT
    u.LANGUAGE,
    COUNT(DISTINCT CASE WHEN lower(e.DEVICE) IN ('macbook pro', 'iphone 5s', 'ipad air') THEN e.USER_ID END) AS N_APPLE_USERS,
    COUNT(DISTINCT e.USER_ID) AS N_TOTAL_USERS
    -- e.EVENT_NAME,except
FROM PLAYBOOK_EVENTS E INNER JOIN PLAYBOOK_USERS u
ON e.USER_ID = u.USER_ID
GROUP BY u.LANGUAGE
ORDER BY N_APPLE_USERS DESC, N_TOTAL_USERS DESC
;