SELECT
    h.NATIONALITY,
    COUNT(DISTINCT u.UNIT_ID)
FROM AIRBNB_HOSTS h INNER JOIN AIRBNB_UNITS u
ON h.HOST_ID = u.HOST_ID
WHERE h.AGE < 30 AND u.UNIT_TYPE = 'Apartment'
GROUP BY h.NATIONALITY
;