-- My solution

WITH CTE1 AS(
    SELECT MAX(e.SALARY) AS ENGG_SALARY FROM
    DB_EMPLOYEE e INNER JOIN DB_DEPT d
    ON e.DEPARTMENT_ID = d.ID
    AND d.DEPARTMENT = 'engineering'
),
CTE2 AS(
    SELECT MAX(e.SALARY) AS MRKT_SALARY FROM
    DB_EMPLOYEE e INNER JOIN DB_DEPT d
    ON e.DEPARTMENT_ID = d.ID
    AND d.DEPARTMENT = 'marketing'
)

SELECT ABS(CTE1.ENGG_SALARY - CTE2.MRKT_SALARY) AS DIFF
FROM CTE1, CTE2
;

--Optimized solution by ChatGPT 
SELECT
    ABS(
        MAX(CASE WHEN d.DEPARTMENT = 'engineering' THEN e.SALARY END) -
        MAX(CASE WHEN d.DEPARTMENT = 'marketing' THEN e.SALARY END)
    ) AS DIFF
FROM DB_EMPLOYEE e
JOIN DB_DEPT d ON e.DEPARTMENT_ID = d.ID;

