SELECT DISTINCT USER_ID FROM(
    SELECT
        USER_ID,
        DATEDIFF(DAY, CREATED_AT, LEAD(CREATED_AT, 1) OVER (PARTITION BY USER_ID ORDER BY CREATED_AT)) AS DAY_DIFFS,
        ROW_NUMBER() OVER (PARTITION BY USER_ID ORDER BY CREATED_AT ASC) AS PURCHASE_NUM
    FROM AMAZON_TRANSACTIONS
) e
WHERE DAY_DIFFS IS NOT NULL AND
DAY_DIFFS <= 7 AND DAY_DIFFS > 0
AND PURCHASE_NUM = 1
ORDER BY USER_ID ASC
;