SELECT
    FROM_USER,
    COUNT(TO_USER) AS EMAILS_SENT,
    ROW_NUMBER() OVER (ORDER BY COUNT(TO_USER) DESC)
FROM GOOGLE_GMAIL_EMAILS
GROUP BY FROM_USER
ORDER BY EMAILS_SENT DESC, FROM_USER ASC
;