-- My solution
SELECT DISTINCT USER_ID FROM
(
    SELECT
        USER_ID,
        RECORD_DATE,
        LEAD(RECORD_DATE, 1) OVER (PARTITION BY USER_ID ORDER BY RECORD_DATE ASC) AS DATE_2,
        LEAD(RECORD_DATE, 2) OVER (PARTITION BY USER_ID ORDER BY RECORD_DATE ASC) AS DATE_3
    FROM SF_EVENTS
)E
WHERE DATEDIFF(DAY, RECORD_DATE, DATE_2) = 1
AND DATEDIFF(DAY, DATE_2, DATE_3) = 1
;

--Optimized solution
SELECT DISTINCT USER_ID
FROM (
    SELECT
        USER_ID,
        RECORD_DATE,
        ROW_NUMBER() OVER (
            PARTITION BY USER_ID
            ORDER BY RECORD_DATE
        ) AS rn
    FROM SF_EVENTS
) t
GROUP BY USER_ID, DATEADD(DAY, -rn, RECORD_DATE)
HAVING COUNT(*) > 2
