WITH CTE1 AS(
    SELECT
        VOTER,
        CANDIDATE,
        COUNT(CANDIDATE) OVER (PARTITION BY VOTER) AS TOTAL_CANDIDATES_VOTED_FOR,
        COUNT(VOTER) OVER(PARTITION BY CANDIDATE) AS TOTAL_PERSONS_VOTED_BY
    FROM VOTING_RESULTS
    WHERE CANDIDATE IS NOT NULL
),

CTE2 AS(
    SELECT
        VOTER,
        CANDIDATE,
        TOTAL_CANDIDATES_VOTED_FOR,
        1/ROUND(CAST(TOTAL_CANDIDATES_VOTED_FOR AS FLOAT), 3) AS PERCENT_OF_VOTE_RECEIVED,
        TOTAL_PERSONS_VOTED_BY
    FROM CTE1
),

CTE3 AS(
    SELECT
        DISTINCT CANDIDATE,
        SUM(PERCENT_OF_VOTE_RECEIVED) OVER(PARTITION BY CANDIDATE) AS TOTAL_VOTES_RECEIVED
    FROM CTE2
)

SELECT CANDIDATE FROM CTE3
WHERE TOTAL_VOTES_RECEIVED = (SELECT MAX(TOTAL_VOTES_RECEIVED) FROM CTE3)
ORDER BY TOTAL_VOTES_RECEIVED DESC
;