-- WITH CTES

WITH CTE1 AS(
    SELECT
        CONCAT(u.USER_FIRSTNAME, ' ', u.USER_LASTNAME) AS FULL_NAME,
        COUNT(DISTINCT u.VIDEO_ID) AS DISTINCT_VIDEO_COUNTS
    FROM USER_FLAGS u INNER JOIN FLAG_REVIEW f
    ON u.FLAG_ID = f.FLAG_ID
    WHERE f.REVIEWED_OUTCOME = 'APPROVED'
    GROUP BY CONCAT(u.USER_FIRSTNAME, ' ', u.USER_LASTNAME)
),
CTE2 AS(
    SELECT
    FULL_NAME,
    DISTINCT_VIDEO_COUNTS,
    RANK() OVER (ORDER BY DISTINCT_VIDEO_COUNTS DESC) AS VIDEO_RANK
    FROM CTE1
)

SELECT
    FULL_NAME
FROM CTE2
WHERE VIDEO_RANK = 1
;

-- WITHOUT CTES, USING TOP 1 WITH TIES
SELECT TOP 1 WITH TIES
    FULL_NAME
FROM(
    SELECT
        CONCAT(u.USER_FIRSTNAME, ' ', u.USER_LASTNAME) AS FULL_NAME,
        COUNT(DISTINCT u.VIDEO_ID) AS DISTINCT_VIDEO_COUNTS
    FROM USER_FLAGS u INNER JOIN FLAG_REVIEW f
    ON u.FLAG_ID = f.FLAG_ID
    WHERE f.REVIEWED_OUTCOME = 'APPROVED'
    GROUP BY CONCAT(u.USER_FIRSTNAME, ' ', u.USER_LASTNAME)
)e
ORDER BY DISTINCT_VIDEO_COUNTS DESC
;