SELECT TOP 5
    PRODUCT_ID,
    SUM(COST_IN_DOLLARS * UNITS_SOLD) AS REVENUE
FROM ONLINE_ORDERS
WHERE 
YEAR(DATE_SOLD) = 2022 AND MONTH(DATE_SOLD) BETWEEN 1 AND 6
GROUP BY PRODUCT_ID
ORDER BY REVENUE DESC
;