--PostgreSQL

SELECT
  ROUND(CAST(SUM(PRODUCT) / SUM(ORDER_OCCURRENCES) AS NUMERIC), 1) AS MEAN
FROM(
SELECT
  ORDER_OCCURRENCES,
  ITEM_COUNT * ORDER_OCCURRENCES AS PRODUCT
FROM ITEMS_PER_ORDER
) E
;