SELECT
  CATEGORY,
  PRODUCT,
  "TOTAL_SPEND"
FROM(
    SELECT
        CATEGORY,
        PRODUCT,
        SUM(SPEND) AS "TOTAL_SPEND",
        RANK() OVER (PARTITION BY CATEGORY ORDER BY SUM(SPEND) DESC) AS SPEND_RANK
    FROM PRODUCT_SPEND
    WHERE EXTRACT(YEAR FROM TRANSACTION_DATE) = '2022'
    GROUP BY CATEGORY, PRODUCT
) E
WHERE SPEND_RANK < 3
;