SELECT USER_ID FROM
(
  SELECT
    USER_ID,
    AMOUNT,
    TRANSACTION_DATE,
    ROW_NUMBER() OVER (PARTITION BY USER_ID ORDER BY TRANSACTION_DATE ASC) AS SPREE
  FROM TRANSACTIONS
)C
WHERE SPREE = 3;