--PostgreSQL

SELECT
  TRANSACTION_DATE,
  USER_ID,
  COUNT(PRODUCT_ID) AS PURCHASE_COUNT
FROM(
  SELECT
    USER_ID,
    PRODUCT_ID,
    TRANSACTION_DATE,
    DENSE_RANK() OVER (PARTITION BY USER_ID ORDER BY TRANSACTION_DATE DESC) AS TRANS_RANK
  FROM USER_TRANSACTIONS
)T
WHERE TRANS_RANK = 1
GROUP BY TRANSACTION_DATE, USER_ID
;