--PostgreSQL

WITH CTE1 AS(
  SELECT
    -- SERVER_ID,
    STATUS_TIME,
    -- SESSION_STATUS,
    CASE
      WHEN SESSION_STATUS = 'start' THEN LEAD(STATUS_TIME, 1) OVER(PARTITION BY SERVER_ID ORDER BY STATUS_TIME ASC)
    END AS SESSION_STOP_TIME
  FROM SERVER_UTILIZATION
  -- ORDER BY SERVER_ID ASC, STATUS_TIME ASC
)

SELECT
  CAST(
    SUM(
        EXTRACT(EPOCH FROM SESSION_STOP_TIME - STATUS_TIME) / (60 * 60 * 24)
        ) AS INTEGER
    ) AS DAYS
FROM CTE1
WHERE SESSION_STOP_TIME IS NOT NULL
;