--PostgreSQL

SELECT
  H.TICKER,
  TO_CHAR(H.DATE, 'Mon-YYYY') AS HIGHEST_MNTH,
  H.OPEN AS HIGHEST_OPEN,
  TO_CHAR(L.DATE, 'Mon-YYYY') AS LOWEST_MNTH,
  L.OPEN AS LOWEST_OPEN
  
FROM STOCK_PRICES H INNER JOIN STOCK_PRICES L ON H.TICKER = L.TICKER

WHERE L.OPEN = (
  SELECT
  MIN(OPEN)
  FROM STOCK_PRICES
  WHERE TICKER = L.TICKER
  GROUP BY TICKER
)
AND H.OPEN = (
  SELECT
  MAX(OPEN)
  FROM STOCK_PRICES
  WHERE TICKER = H.TICKER
  GROUP BY TICKER
)
ORDER BY H.TICKER ASC
;