--PostgreSQL 14

SELECT
  MANUFACTURER,
  COUNT(DRUG) as DRUG_COUNT,
  SUM(COGS - TOTAL_SALES) AS TOTAL_LOSS
FROM PHARMACY_SALES
WHERE TOTAL_SALES < COGS
GROUP BY MANUFACTURER
ORDER BY TOTAL_LOSS DESC