--PostgreSQL 14

SELECT
  MANUFACTURER,
  CONCAT('$',ROUND(SUM(TOTAL_SALES)/1000000,0),' million') as SALE
FROM PHARMACY_SALES
GROUP BY MANUFACTURER
ORDER BY SUM(TOTAL_SALES) DESC, MANUFACTURER ASC
;