SELECT
  DISTINCT I.DEPARTMENT_ID,
  II.PAYMENT_DATE,
  CASE
    WHEN I.AVERAGE_DEPT_SALARY < II.AVG_COMP_SALARY THEN 'lower'
    WHEN I.AVERAGE_DEPT_SALARY > II.AVG_COMP_SALARY THEN 'higher'
    WHEN I.AVERAGE_DEPT_SALARY = II.AVG_COMP_SALARY THEN 'same'
  END AS COMPARISON
FROM
(
  SELECT
    E.DEPARTMENT_ID,
    SUM(S.AMOUNT) / COUNT(E.EMPLOYEE_ID) AS AVERAGE_DEPT_SALARY
  FROM EMPLOYEE E LEFT JOIN SALARY S ON E.EMPLOYEE_ID = S.SALARY_ID
  GROUP BY E.DEPARTMENT_ID
) I
CROSS JOIN
(
  SELECT
    TO_CHAR(S.PAYMENT_DATE, 'MM-YYYY') as PAYMENT_DATE,
    SUM(S.AMOUNT) / COUNT(S.EMPLOYEE_ID) AS AVG_COMP_SALARY
  FROM SALARY S
  WHERE 
  EXTRACT(YEAR FROM S.PAYMENT_DATE) = 2024 AND
  EXTRACT(MONTH FROM S.PAYMENT_DATE) = 3
  GROUP BY PAYMENT_DATE
) II
;