--PostgreSQL 14

SELECT 
  DEPARTMENT_NAME,
  NAME,
  SALARY
FROM(
  SELECT
    E.EMPLOYEE_ID,
    E.NAME,
    E.SALARY,
    E.DEPARTMENT_ID,
    D.DEPARTMENT_NAME,
    DENSE_RANK() OVER (PARTITION BY D.DEPARTMENT_NAME ORDER BY SALARY DESC) AS SALARY_RANK
  FROM EMPLOYEE E INNER JOIN DEPARTMENT D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
  ORDER BY E.SALARY DESC
) E
WHERE SALARY_RANK < 4
ORDER BY DEPARTMENT_NAME ASC, SALARY DESC, NAME ASC
;