--PostgreSQL

SELECT
  MONTH_NUM,
  COUNT(DISTINCT USER_ID) AS MONTHLY_ACTIVE_USERS
FROM
(
  SELECT
    USER_ID,
    EVENT_DATE,
    MONTH_NUM,
    LAG(MONTH_NUM, 1) OVER(PARTITION BY USER_ID ORDER BY EXTRACT(MONTH FROM EVENT_DATE)) AS PREV_MONTH
  FROM
  (
    SELECT
      USER_ID,
      EVENT_ID,
      EVENT_TYPE,
      EVENT_DATE,
      EXTRACT(MONTH FROM EVENT_DATE) AS MONTH_NUM
    FROM USER_ACTIONS
  )E
)F
WHERE MONTH_NUM = 7 AND PREV_MONTH IS NOT NULL AND PREV_MONTH != MONTH_NUM
GROUP BY MONTH_NUM
;