--PostgreSQL

SELECT
  USER_ID,
  DATE_DIFF
FROM(
  SELECT
    USER_ID,
    MAX(POST_DATE::DATE) - MIN(POST_DATE::DATE) AS DATE_DIFF
  FROM POSTS
  WHERE EXTRACT(YEAR FROM POST_DATE) = '2021'
  GROUP BY USER_ID
)P
WHERE DATE_DIFF > 0
;