--PostgreSQL

SELECT
  APP_ID,
  ROUND((100.0 * SUM(CLICK) / SUM(IMPRESSION))::NUMERIC, 2) AS CTR
FROM(
  SELECT
    APP_ID,
    EVENT_TYPE,
    CASE
      WHEN EVENT_TYPE = 'impression' then 1 ELSE 0
    END AS IMPRESSION,
    CASE
      WHEN EVENT_TYPE = 'click' THEN 1 ELSE 0
    END AS CLICK
  FROM EVENTS
  WHERE EXTRACT(YEAR FROM TIMESTAMP) = '2022'
  ORDER BY APP_ID
)A
GROUP BY APP_ID;