--PostgreSQL

SELECT
CARD_NAME, ISSUED_AMOUNT
FROM(
  SELECT
    ISSUE_MONTH,
    ISSUE_YEAR,
    CARD_NAME,
    ISSUED_AMOUNT,
    RANK() OVER(PARTITION BY CARD_NAME ORDER BY ISSUE_YEAR ASC, ISSUE_MONTH ASC) AS ISSUE_RANK
  FROM MONTHLY_CARDS_ISSUED
)C
WHERE ISSUE_RANK = 1
ORDER BY ISSUED_AMOUNT DESC
;