--MySQL

SELECT COUNT(DUPL) AS DUPLICATE_COMPANIES FROM (
SELECT
  COMPANY_ID,
  TITLE,
  DESCRIPTION,
  ROW_NUMBER() OVER (PARTITION BY COMPANY_ID, TITLE, DESCRIPTION) AS DUPL
FROM JOB_LISTINGS
ORDER BY COMPANY_ID
) I
WHERE DUPL > 1;