--PostgreSQL

WITH CTE1 AS(
  SELECT
    T1.TOPPING_NAME AS TOP1,
    T2.TOPPING_NAME AS TOP2,
    T3.TOPPING_NAME AS TOP3,
    T1.INGREDIENT_COST + T2.INGREDIENT_COST + T3.INGREDIENT_COST AS TOTAL_COST
  FROM PIZZA_TOPPINGS T1
  CROSS JOIN PIZZA_TOPPINGS T2 CROSS JOIN PIZZA_TOPPINGS T3
  WHERE T1.TOPPING_NAME != T2.TOPPING_NAME
        AND T2.TOPPING_NAME != T3.TOPPING_NAME
        AND T3.TOPPING_NAME != T1.TOPPING_NAME
),

CTE2 AS(
  SELECT
  CASE
    WHEN TOP1 < TOP2 AND TOP2 < TOP3 THEN CONCAT(TOP1, ",", TOP2, ",", TOP3)
    WHEN TOP1 < TOP3 AND TOP3 < TOP2 THEN CONCAT(TOP1, ",", TOP3, ",", TOP2)
    WHEN TOP2 < TOP1 AND TOP1 < TOP3 THEN CONCAT(TOP2, ",", TOP1, ",", TOP3)
    WHEN TOP2 < TOP3 AND TOP3 < TOP1 THEN CONCAT(TOP2, ",", TOP3, ",", TOP1)
    WHEN TOP3 < TOP2 AND TOP2 < TOP1 THEN CONCAT(TOP3, ",", TOP2, ",", TOP1)
    WHEN TOP3 < TOP1 AND TOP1 < TOP2 THEN CONCAT(TOP3, ",", TOP1, ",", TOP2)
  END AS COMB_TOP,
  TOTAL_COST
FROM CTE1
)

SELECT 
  DISTINCT COMB_TOP AS PIZZA, 
  TOTAL_COST
FROM CTE2
ORDER BY TOTAL_COST DESC, COMB_TOP ASC
;
