--PostgreSQL

SELECT * FROM(
  SELECT
    SENDER_ID,
    COUNT(MESSAGE_ID) AS MESSAGE_COUNT
  FROM MESSAGES
  WHERE EXTRACT(YEAR FROM SENT_DATE) = '2022' AND EXTRACT(MONTH FROM SENT_DATE) = 8
  GROUP BY SENDER_ID
) M
ORDER BY MESSAGE_COUNT DESC LIMIT 2
;