--PostgreSQL 14

SELECT CUSTOMER_ID FROM
(
  SELECT
    C.CUSTOMER_ID,
    COUNT(DISTINCT P.PRODUCT_CATEGORY) AS COUNT_PRODUCT_CATEGORIES
  FROM CUSTOMER_CONTRACTS C INNER JOIN PRODUCTS P ON C.PRODUCT_ID = P.PRODUCT_ID
  GROUP BY C.CUSTOMER_ID
)E
WHERE E.COUNT_PRODUCT_CATEGORIES = (
SELECT COUNT(DISTINCT PRODUCT_CATEGORY) FROM PRODUCTS
)
;