--MySQL

SELECT L.LAPTOP_VIEWS, M.MOBILE_VIEWS FROM
(
    SELECT COUNT(VIEW_TIME) AS LAPTOP_VIEWS
    FROM VIEWERSHIP
    WHERE DEVICE_TYPE = 'laptop'
) L
CROSS JOIN
(
    SELECT COUNT(VIEW_TIME) AS MOBILE_VIEWS
    FROM VIEWERSHIP
    WHERE DEVICE_TYPE in ('tablet','phone')
) M
;