--PostgreSQL

SELECT * FROM(
    SELECT
        U.CITY,
        COUNT(T.ORDER_ID) AS TOTAL_ORDERS
    FROM TRADES T INNER JOIN USERS U ON T.USER_ID = U.USER_ID
    WHERE T.STATUS = 'Completed'
    GROUP BY U.CITY
)C
ORDER BY TOTAL_ORDERS DESC LIMIT 3
;