--PostgreSQL 14

WITH CTE_SEND AS(
SELECT
  B.AGE_BUCKET,
  -- A.ACTIVITY_ID,
  -- A.ACTIVITY_TYPE,
  sum(A.TIME_SPENT) as SEND_TIME
  
FROM activities A INNER JOIN age_breakdown B ON A.USER_ID = B.USER_ID
WHERE A.ACTIVITY_TYPE = 'send'
GROUP BY B.AGE_BUCKET
),

CTE_OPEN AS(
SELECT
  B.AGE_BUCKET,
  -- A.ACTIVITY_ID,
  -- A.ACTIVITY_TYPE,
  sum(A.TIME_SPENT) as OPEN_TIME
  
FROM activities A INNER JOIN age_breakdown B ON A.USER_ID = B.USER_ID
WHERE A.ACTIVITY_TYPE = 'open'
GROUP BY B.AGE_BUCKET
)

,CTE_ALL AS(
  SELECT
    B.AGE_BUCKET,
    -- A.ACTIVITY_ID,
    -- A.ACTIVITY_TYPE,
    sum(A.TIME_SPENT) as ALL_TIME
  
  FROM activities A INNER JOIN age_breakdown B ON A.USER_ID = B.USER_ID
  GROUP BY B.AGE_BUCKET
)
SELECT 
  A.AGE_BUCKET,
  -- A.ALL_TIME,
  ROUND(S.SEND_TIME/(S.SEND_TIME + O.OPEN_TIME) * 100.0, 2) AS SEND_PERC,
  ROUND(O.OPEN_TIME/(S.SEND_TIME + O.OPEN_TIME) * 100.0, 2) AS OPEN_PERC
FROM 
CTE_ALL A INNER JOIN CTE_SEND S ON A.AGE_BUCKET = S.AGE_BUCKET 
INNER JOIN CTE_OPEN O ON S.AGE_BUCKET = O.AGE_BUCKET
;