--PostgreSQL 14

SELECT
  ARTIST_NAME,
  SONG_RANK
FROM
(
  SELECT
    A.ARTIST_ID,
    A.ARTIST_NAME,
    DENSE_RANK() OVER (ORDER BY COUNT(S.SONG_ID) DESC) AS SONG_RANK
  FROM ARTISTS A INNER JOIN SONGS S ON A.ARTIST_ID = S.ARTIST_ID
  INNER JOIN GLOBAL_SONG_RANK G ON S.SONG_ID = G.SONG_ID
  WHERE G.RANK <= 10
  GROUP BY A.ARTIST_ID, A.ARTIST_NAME
  ORDER BY COUNT(S.SONG_ID) DESC
) E
WHERE SONG_RANK < 6
;