--PostgreSQL

WITH CTE1 AS(
  SELECT
    TRANSACTION_TIMESTAMP,
    LAG(TRANSACTION_TIMESTAMP, 1) 
        OVER(PARTITION BY MERCHANT_ID, CREDIT_CARD_ID, AMOUNT ORDER BY TRANSACTION_TIMESTAMP ASC) AS PREV_DUPLICATE_PAYMENT
  FROM TRANSACTIONS
  ORDER BY MERCHANT_ID ASC
)

SELECT
  SUM(
    CASE 
        WHEN EXTRACT(EPOCH FROM TRANSACTION_TIMESTAMP - PREV_DUPLICATE_PAYMENT)/60 <= 10 THEN 1 
        ELSE 0 
    END
    ) AS DUPLICATES
FROM CTE1
;