--PostgreSQL 14

SELECT
ROUND(SUM(SIGNUP_CONFIRMATION)/COUNT(*), 2) AS ACTIVATION_RATE
FROM
(
  SELECT
    E.EMAIL_ID,
    E.USER_ID,
    T.TEXT_ID,
    T.SIGNUP_ACTION,
    CASE
      WHEN SIGNUP_ACTION = 'Confirmed' then 1.0
      ELSE 0.0
    END AS SIGNUP_CONFIRMATION
  FROM EMAILS E INNER JOIN TEXTS T ON E.EMAIL_ID = T.EMAIL_ID
) E
;