--PostgreSQL

SELECT
  USER_ID
  ,TWEET_DATE
  -- ,TWEET_COUNT
  ,ROUND(AVG(TWEET_COUNT) OVER (PARTITION BY USER_ID ORDER BY TWEET_DATE ASC ROWS BETWEEN 2 PRECEDING AND CURRENT ROW), 2) AS ROLLING_AVG_3D
FROM TWEETS
ORDER BY USER_ID ASC, TWEET_DATE ASC