--PostgreSQL

SELECT
  TWEET_BUCKET,
  COUNT(USER_ID) AS USERS_NUM
FROM(
  SELECT
    COUNT(TWEET_ID) AS TWEET_BUCKET,
    USER_ID
  FROM TWEETS
  WHERE EXTRACT(YEAR FROM TWEET_DATE) = '2022'
  GROUP BY USER_IDVSC
)I
GROUP BY TWEET_BUCKET
;
