--PostgreSQL 14

SELECT 
  USER_ID,
  SPEND,
  TRANSACTION_DATE
FROM (
  SELECT
    USER_ID,
    SPEND,
    TRANSACTION_DATE,
    ROW_NUMBER() OVER (PARTITION BY USER_ID ORDER BY TRANSACTION_DATE) AS SPEND_NUMBER
  FROM TRANSACTIONS
)E
WHERE SPEND_NUMBER = 3;