--PostgreSQL 14

SELECT COUNT(POLICY_HOLDER_ID) AS POLICY_HOLDER_COUNT FROM
(
  SELECT
    POLICY_HOLDER_ID,
    COUNT(CASE_ID)
  FROM CALLERS
  GROUP BY POLICY_HOLDER_ID
  HAVING COUNT(CASE_ID) > 2
)E
;