WITH CTE1 AS(
SELECT
  C.CALLER_ID,
  C.RECEIVER_ID,
  C.CALL_TIME,
  IC.COUNTRY_ID AS CALLER_COUNTRY_ID,
  RC.COUNTRY_ID AS RECEIVER_COUNTRY_ID
FROM 
PHONE_CALLS C INNER JOIN PHONE_INFO IC ON C.CALLER_ID = IC.CALLER_ID
INNER JOIN PHONE_INFO RC ON C.RECEIVER_ID = RC.CALLER_ID
),

CTE2 AS(
  SELECT
    CALLER_ID,
    RECEIVER_ID,
    CALL_TIME,
    CALLER_COUNTRY_ID,
    RECEIVER_COUNTRY_ID
  FROM CTE1
  WHERE CALLER_COUNTRY_ID != RECEIVER_COUNTRY_ID
)

SELECT ROUND((
  (SELECT CAST(COUNT(*)AS FLOAT) FROM CTE2)/
  (SELECT CAST(COUNT(*)AS FLOAT) FROM CTE1) * 100)::NUMERIC
  ,1);