SELECT
  EXTRACT(YEAR FROM TRANSACTION_DATE) AS YEAR,
  PRODUCT_ID,
  SPEND AS CURR_YEAR_SPEND,
  PREVIOUS_YEAR_SPEND,
  ROUND(((SPEND - PREVIOUS_YEAR_SPEND)/PREVIOUS_YEAR_SPEND * 100)::NUMERIC, 2) AS YOY_RATE
FROM(
  SELECT
    PRODUCT_ID,
    SPEND,
    TRANSACTION_DATE,
    LAG(EXTRACT(YEAR FROM TRANSACTION_DATE), 1) OVER(PARTITION BY PRODUCT_ID ORDER BY EXTRACT(YEAR FROM TRANSACTION_DATE)) AS PREVIOUS_YEAR_NUM,
    LAG(SPEND, 1) OVER(PARTITION BY PRODUCT_ID ORDER BY EXTRACT(YEAR FROM TRANSACTION_DATE)) AS PREVIOUS_YEAR_SPEND
  FROM USER_TRANSACTIONS
  ORDER BY PRODUCT_ID ASC
)E
;