WITH CTE1 AS(
  SELECT
  	PRODUCT_ID,
  	CASE
  		WHEN PRICE < 100 THEN 'Low Price'
  		WHEN PRICE >= 100 AND PRICE <= 500 THEN 'Medium Price'
  		WHEN PRICE > 500 THEN 'High Price'
  	END AS CATEGORY
 FROM PRODUCTS
)
SELECT
    CATEGORY,
	COUNT(PRODUCT_ID) AS Product_Count
FROM CTE1
GROUP BY CATEGORY
ORDER BY COUNT(PRODUCT_ID) DESC
;