SELECT * FROM(
  SELECT * FROM PRODUCT_REVIEWS
  WHERE
      UPPER(REVIEW_TEXT) LIKE '%AMAZING%'
      OR UPPER(REVIEW_TEXT) LIKE '%EXCELLENT%'
) e
WHERE
UPPER(REVIEW_TEXT) NOT LIKE '%NOT AMAZING%'
AND UPPER(REVIEW_TEXT) NOT LIKE '%NOT EXCELLENT%'
ORDER BY REVIEW_ID ASC
;