SELECT
	l.LOAN_ID,
    MAX(l.LOAN_AMOUNT) AS LOAN_AMOUNT,
    MAX(l.DUE_DATE) AS DUE_DATE,
    CASE
    	WHEN SUM(p.AMOUNT_PAID) = MAX(l.LOAN_AMOUNT) THEN 1
        ELSE 0
	END AS FULLY_PAID_FLAG,
    CASE
    	WHEN SUM(p.AMOUNT_PAID) = MAX(l.LOAN_AMOUNT) AND MAX(p.PAYMENT_DATE) <= MAX(l.DUE_DATE) THEN 1
        ELSE 0
	END AS ON_TIME_FLAG
FROM LOANS l LEFT JOIN PAYMENTS p ON l.LOAN_ID = p.LOAN_ID
GROUP BY l.LOAN_ID
;