SELECT
	c.CATEGORY_NAME,
	CASE
    	WHEN SUM(s.AMOUNT) IS NULL THEN 0
    	ELSE SUM(s.AMOUNT)
    END AS TOTAL_SALES
FROM SALES s RIGHT JOIN CATEGORIES c
ON s.CATEGORY_ID = c.CATEGORY_ID
GROUP BY c.CATEGORY_NAME
ORDER BY SUM(s.AMOUNT)
;