SELECT
	d.DEPARTMENT_NAME,
    ROUND(AVG(CAST(e.SALARY AS DECIMAL(10, 4))), 2) AS AVG_SALARY
FROM EMPLOYEES e INNER JOIN DEPARTMENTS d
ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
GROUP BY d.DEPARTMENT_NAME
HAVING COUNT(e.EMPLOYEE_ID) > 2
ORDER BY AVG_SALARY DESC
;