SELECT
    COMPANY_NAME,
    PRODUCTS_2020 - PRODUCTS_2019 AS LAUNCH_DIFF
FROM (
    SELECT
        COMPANY_NAME,
        SUM(CASE WHEN YEAR = 2019 THEN 1 ELSE 0 END) AS PRODUCTS_2019,
        SUM(CASE WHEN YEAR = 2020 THEN 1 ELSE 0 END) AS PRODUCTS_2020
    FROM CAR_LAUNCHES
    GROUP BY COMPANY_NAME
)E
;