WITH CTE1 AS (
    SELECT 
        CONCAT(USER_FIRSTNAME, '_', USER_LASTNAME) AS UNIQUE_USERS,
        VIDEO_ID,
        FLAG_ID
    FROM USER_FLAGS
    WHERE FLAG_ID IS NOT NULL
)

SELECT
    VIDEO_ID, COUNT(DISTINCT UNIQUE_USERS) AS NUM_UNIQUE_USERS
FROM CTE1
GROUP BY VIDEO_ID
;