-- My solution = 0.01590 seconds

WITH CTE1 AS(
    SELECT
        SURVIVED,
        COUNT(SURVIVED) AS FIRST_CLASS
    FROM TITANIC
    WHERE PCLASS = 1
    GROUP BY SURVIVED
),
CTE2 AS(
    SELECT
        SURVIVED,
        COUNT(SURVIVED) AS SECOND_CLASS
    FROM TITANIC
    WHERE PCLASS = 2
    GROUP BY SURVIVED
),
CTE3 AS(
    SELECT
        SURVIVED,
        COUNT(SURVIVED) AS THIRD_CLASS
    FROM TITANIC
    WHERE PCLASS = 3
    GROUP BY SURVIVED
)
SELECT
    CTE1.SURVIVED,
    CTE1.FIRST_CLASS,
    CTE2.SECOND_CLASS,
    CTE3.THIRD_CLASS
FROM 
CTE1 INNER JOIN CTE2 ON CTE1.SURVIVED = CTE2.SURVIVED
INNER JOIN CTE3 ON CTE1.SURVIVED = CTE3.SURVIVED
;

--------------------------------------------------------------

-- Improved solution (obtained from ChatGPT) = 0.02143 seconds
SELECT 
    SURVIVED,
    COUNT(CASE WHEN PCLASS = 1 THEN 1 END) AS FIRST_CLASS,
    COUNT(CASE WHEN PCLASS = 2 THEN 1 END) AS SECOND_CLASS,
    COUNT(CASE WHEN PCLASS = 3 THEN 1 END) AS THIRD_CLASS
FROM TITANIC
GROUP BY SURVIVED;
