SELECT TOP 1
    c.FIRST_NAME,
    -- c.ID AS CUST_ID,
    o.ORDER_DATE,
    -- o.TOTAL_ORDER_COST,
    SUM(o.TOTAL_ORDER_COST) OVER (PARTITION BY o.CUST_ID, o.ORDER_DATE) AS SAME_DAY_COSTS
FROM CUSTOMERS c RIGHT JOIN ORDERS o
ON c.ID = o.CUST_ID
AND o.ORDER_DATE BETWEEN '2019-02-01' AND '2019-05-01'
ORDER BY SAME_DAY_COSTS DESC, CUST_ID ASC, ORDER_DATE ASC
;